
package com.thunisoft.parse09xml.receiving.client.tdh6;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DataTransService", targetNamespace = "http://sjzh.swap.tdh/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface DataTransService {


    /**
     * 
     * @param xml
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String getCaseXml09(
        @WebParam(name = "xml", partName = "xml")
        String xml);

    /**
     * 
     * @param xml
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String getZzjg(
        @WebParam(name = "xml", partName = "xml")
        String xml);

    /**
     * 
     * @param xml
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String getWsList(
        @WebParam(name = "xml", partName = "xml")
        String xml);

    /**
     * 
     * @param xml
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String getCaseXml(
        @WebParam(name = "xml", partName = "xml")
        String xml);

    /**
     * 
     * @param xml
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String getDelZip(
        @WebParam(name = "xml", partName = "xml")
        String xml);

    /**
     * 
     * @param xml
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "getDelZip_type2")
    @WebResult(partName = "return")
    public String getDelZipType2(
        @WebParam(name = "xml", partName = "xml")
        String xml);

    /**
     * 
     * @param xml
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String getCaseZip(
        @WebParam(name = "xml", partName = "xml")
        String xml);

    /**
     * 
     * @param xml
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String getWsData(
        @WebParam(name = "xml", partName = "xml")
        String xml);

    /**
     * 
     * @param xml
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String getDailyUpdateCaseList(
        @WebParam(name = "xml", partName = "xml")
        String xml);

    /**
     * 
     * @param xml
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String getCaseList(
        @WebParam(name = "xml", partName = "xml")
        String xml);

    /**
     * 
     * @param xml
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "getCaseXml09_type2")
    @WebResult(partName = "return")
    public String getCaseXml09Type2(
        @WebParam(name = "xml", partName = "xml")
        String xml);

}
